#!/bin/bash

show_help() {
    echo "Usage: extend [OPTION]"
    echo "Create or manage headless Wayland output for VNC."
    echo
    echo "Options:"
    echo "  -h, --help              Show this help message and exit"
    echo "  -r, --remove [TARGET]   Remove a headless monitor. If TARGET is specified,"
    echo "                          remove that specific monitor. Otherwise remove"
    echo "                          the first occurrence of a headless monitor"
    echo "  -d                      Display active monitors"
    echo
    echo "Without options, the script creates a headless output and starts wayvnc."
}

create_headless() {
    hyprctl output create headless
    wayvnc 0.0.0.0 &
    ip route get 1.2.3.4 | awk '{print $7}'
}

remove_headless() {
    if [ -n "$1" ]; then
        if hyprctl monitors | grep -q "$1"; then
            hyprctl output remove "$1"
            echo "Removed $1"
            pkill wayvnc
        else
            echo "Monitor $1 not found"
        fi
    else
        headless_info=$(hyprctl monitors | grep -i "HEADLESS-" | head -n 1)
        if [ -n "$headless_info" ]; then
            headless_number=$(echo "$headless_info" | sed -n 's/.*HEADLESS-\([0-9]\+\).*/\1/p')
            hyprctl output remove "HEADLESS-$headless_number"
            echo "Removed HEADLESS-$headless_number"
            pkill wayvnc
        else
            echo "No HEADLESS monitor found"
        fi
    fi
}

display_monitors() {
    hyprctl monitors
}

case "$1" in
    -h|--help)
        show_help
        ;;
    -r|--remove)
        remove_headless "$2"
        ;;
    -d|--display)
        display_monitors
        ;;
    ""|--create)
        create_headless
        ;;
    *)
        echo "Invalid option. Use --help for usage information."
        exit 1
        ;;
esac
